# Generated by Django 4.2.20 on 2025-03-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
                ('trainings', models.ManyToManyField(to='main_app.training')),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('A', 'AM'), ('P', 'PM')], default='A', max_length=1)),
                ('grain_type', models.CharField(choices=[('WL', 'Weanling'), ('YL', 'Yearling'), ('WK', 'Working'), ('MT', 'Maintenance'), ('SR', 'Senior')], default='WL', max_length=2)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.horse')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
