# Generated by Django 4.2.20 on 2025-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locaton', models.CharField(max_length=100)),
                ('discipline', models.CharField(max_length=100)),
            ],
        ),
    ]
