# Generated by Django 4.2.20 on 2025-03-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_training'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='locaton',
            new_name='location',
        ),
    ]
