# Generated by Django 4.2.20 on 2025-03-17 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_horse_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='image',
        ),
    ]
